### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yaouenvoyage** [edunumsec2/book#110]
### Page

https://dev-apprendre.modulo-info.ch/rep-info/entiers.html

### Que s'est-il passé ?

Il y a une erreur sur [l'image](https://dev-apprendre.modulo-info.ch/_images/4bitsIntegers.svg)

### Quel résultat était attendu ?

Résultat attendu - Corrigé 2x -6

### Sur quel navigateur ?

Autre

**Comment by jppellet** [comment]
En effet, c'est corrigé sur dev. Merci!
