### ISSUE TITLE
@elliotvaucher : panel question et darkmode

### ISSUE THREAD

**Issue by dasilvadds** [edunumsec2/book#32]
https://github.com/edunumsec2/book/blob/54945192ea34d37e7a71800035c9e8caf62299a5/content/appr/theme/rep-info/cours/intro/eleve.md#L196

Les panels questions semble ne pas bien être rendus avec le darkmode, ils sont blanchatre, un peu comme grisés et le texte et difficilement lisible ?!

**Comment by elliotvaucher** [comment]
Solution apportée par le nouveau template en train d'être développé qui comprend un darkmode automatique.
