### ISSUE TITLE
Congruence sur façon de donner des instructions aux élèves.

### ISSUE THREAD

**Issue by jvprof** [edunumsec2/book#35]
Quels sont les règles d'orthographe pour donner des instructions aux élèves ?

- Impératif (faites ceci, écrivez cela)
- indicatif (faire ceci, écrire cela)

Les 2 peuvent être acceptable. mais il faut être uniforme sur le site et à minima sur une page. 

Issue on page /content/ens/theme/algo1/accueil/solutions.html

**Comment by jvprof** [comment]
Solution envisageable:
1. Comité de rédaction --> définir une règle (perso je suis pour l'impératif car plus personnel, moins froid)
2. Members --> corrections page par page.

**Comment by cvangenot** [comment]
Je préfère aussi l'impératif.

**Comment by mihersch** [comment]
Merci pour le feedback, on peut aborder ce point à la prochaine discussion.

**Comment by elliotvaucher** [comment]
@jvprof : le problème est en train d'être traité. On définit actuellement une charte d'écriture, qu'on pourra par la suite partager à tout le monde pour homogénéiser les contenus. Merci ! 

Je ferme l'issue.
