### ISSUE TITLE
[Bug]: Problème avec le Glossaire

### ISSUE THREAD

**Issue by gregoiregavin** [edunumsec2/book#54]
### Page

Toutes les pages

### Que s'est-il passé ?

Sur le nouveau book Furo, Windows, l'extension Glossary génère une erreur lors du build.

Le site se build bien, mais les mots glossaires s'affichent comme suit :

![image](https://user-images.githubusercontent.com/12733352/158773524-80129824-b57a-420e-94b2-5783a47a9780.png)

### Quel résultat était attendu ?

Pas d'erreur et affichage propre de l'extension.

### Sur quel navigateur ?

Firefox

### Quel format ?

Mobile, Desktop

### Logs pertinents

```shell
Extension error (glossary):
Handler <function load_glossary_csv at 0x00000213FE7F0AF0> for event 'env-before-read-docs' threw an exception (exception: 'charmap' codec can't decode byte 0x81 in position 2415: character maps to <undefined>)
Command exited with exit code: 2
```

### Code of Conduct

- [x] J'accepte de suivre le code de conduite.

**Comment by redelmann** [comment]
Fixed in commit 18e8338ba59230b874c4ac0c11f7cc6d83f5c177
