### ISSUE TITLE
[Design]: module Questions

### ISSUE THREAD

**Issue by gregoiregavin** [edunumsec2/book#59]
### Page

Par exemple : /prog1/dessiner.html

### Que s'est-il passé ?

Branche 'migration'.

Le `@media (prefers-color-scheme: dark)` dans src/exts/static/questions.css n'a pas d'impact lorsque l'on change de thème : 

![image](https://user-images.githubusercontent.com/12733352/159251157-6de4465b-c38a-43ef-99c0-11dff0593f0d.png)

### Quel résultat était attendu ?

Pouvoir lire :') 

Plus globalement, je ne comprends pas vraiment pourquoi ça ne fonctionne pas. Selon la [doc de Furo](https://pradyunsg.me/furo/customisation/colors/), le thème se base sur prefers-color-scheme...

### Sur quel navigateur ?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Autre

### Quel format ?

Mobile, Desktop

### Code of Conduct

- [X] J'accepte de suivre le code de conduite.

**Comment by redelmann** [comment]
Ce qui se passe c'est que le bouton dans le theme Furo n'est pas directement lié au dark mode du système.

**Comment by redelmann** [comment]
En mode "auto", la configuration système est utilisée. Pour mettre le style de la version "dark" de furo dans nos CSS, préfixer le selecteur par `body[data-theme="dark"]`?

**Comment by gregoiregavin** [comment]
Merci pour les explications et le push fix, ça fonctionne !

**Comment by gregoiregavin** [comment]
Comme discuté, on va voir pour une solution alternative car nos feuilles de styles vont prendre beaucoup trop cher avec cette solution.
