### ISSUE TITLE
[Bug]: chargement de fichiers Excel

### ISSUE THREAD

**Issue by christophedumas2011** [edunumsec2/book#66]
### Page

https://dev-enseigner.modulo-info.ch/rep-info/activ/echantillonnage.html

### Que s'est-il passé ?

Auparavant j'utilisais Download pour permettre le téléchargement d'un fichier excel (fin de la page).
[Devoir - évaluation maison de type quizz moodle](activ/media/QuizzEch.ods) ne fonctionne pas...

### Quel résultat était attendu ?

Résultat attendu : chargement du fichier Excel ...

### Sur quel navigateur ?

Safari

### Quel format ?

Desktop

### Code of Conduct

- [X] J'accepte de suivre le code de conduite.

**Comment by elliotvaucher** [comment]
@christophedumas2011 : merci ! Normalement le problème est résolu par ce commit : 856fa586eef79445ca53a443356862f5de9dfd82.
