### ISSUE TITLE
[Contenu]: Virerions-nous le "copyright" pour mettre un CC-by-nc à la place?

### ISSUE THREAD

**Issue by jppellet** [edunumsec2/book#69]
### Page

Toutes

### Quel est le problème relevé ?

Le copyright du bas de page semble contredire notre licence

### Quelle est votre suggestion ?

Virer le copyright et montrer le petit logo de notre licence (en français)

<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

### Code of Conduct

- [X] J'accepte de suivre le code de conduite.

**Comment by elliotvaucher** [comment]
@jppellet Oui, tu as tout à fait raison. Pas fait attention à ça pendant la migration. J'ai modifié avec ce commit : cfd965e7c9ce39bd8e2ad0d94f8383a612fd77b9

**Comment by jppellet** [comment]
Je crois qu'on aura besoin d'une autre motif, parce qu'on a toujours «Copyright © 2022» en pied de page.

**Comment by jppellet** [comment]
Je serais aussi pour virer l'«autopub» de Sphinx de chaque page («Built with Sphinx and @pradyunsg's Furo theme»), on peut le mettre une fois ailleurs si on fait un colophon ou un truc comme ça.

**Comment by pradyunsg** [comment]
`html_show_sphinx`

**Comment by elliotvaucher** [comment]
@jppellet @pradyunsg : C'est bon ! Merci beaucoup. 

Modifié ici : cd9bad4e4df9f38aec3ddab676a0d5ee87359ed9

**Comment by jppellet** [comment]
Je propose de mettre `html_show_copyright` carrément à `False`. Je ne suis pas super au clair sur le côté légal, mais j'ai l'impression que la juxtaposition de «Copyright» et «CC quelque chose» est bizarre.

**Comment by elliotvaucher** [comment]
Oui, ça me paraît ok aussi. C'est fait ici : b7f83052a48534bae6af6c57aa5cee8902a8ce41
