### ISSUE TITLE
[Bug]: Source markdown servie avec mauvaise indication de l'encodage

### ISSUE THREAD

**Issue by jppellet** [edunumsec2/book#70]
### Page

Toutes

### Que s'est-il passé ?

Le pied de page permet de voir le source Markdown de la page. C'est un document texte avec l'encodage UTF-8. Mais mon browser ne l'affiche pas en UTF-8, ce qui cause des soucis d'affichage.

### Quel résultat était attendu ?

La page devrait être service avec ce header:

`Content-Type: text/plain; charset=utf-8`

### Sur quel navigateur ?

Safari

### Quel format ?

Desktop

### Code of Conduct

- [X] J'accepte de suivre le code de conduite.

**Comment by elliotvaucher** [comment]
@jppellet : merci pour l'indication. 

J'ai cherché mais n'ai pas trouvé l'endroit où modifier ce paramètre. @redelmann @gregoiregavin : une idée ?

**Comment by redelmann** [comment]
Il faut mettre la ligne suivante dans un .htaccess:

`AddCharset UTF-8 .txt`

On peut mettre dans le .htaccess de chaque site, voire le mettre dans un .htaccess global (si ça marche).

**Comment by elliotvaucher** [comment]
@redelmann : merci. C'est effectué.
