### ISSUE TITLE
Correction tampons

### ISSUE THREAD

**Issue by ph3n4t3s** [edunumsec2/book#75]
### Page

https://apprendre.modulo-info.ch/content/appr/theme/prog1/cours/5_list/list.html

### Quel est le problème relevé ?

Erreur sur le code :
tampon = ['h', 'a']
tampon.append('m')
print(tampon)
pop(0)
print(tampon)

### Quelle est votre suggestion ?

Correction

tampon = ['h', 'a']
tampon.append('m')
print(tampon)
tampon.pop(0)
print(tampon)

### Code of Conduct

- [X] J'accepte de suivre le code de conduite.

**Comment by elliotvaucher** [comment]
@ph3n4t3s : merci pour le signalement. Ca a été modifié dans ce commit : 0095f97d969db479464700c97b08e0ce104143df. 

Je mets en ligne le plus rapidement possible. 

J'en profite pour signaler qu'une version plus à jour des ressources est disponible sous dev-apprendre.modulo-info.ch. On va bientôt faire passer celle-ci comme version officielle. 

À bientôt.
