### ISSUE TITLE
[Bug]: .gitignore

### ISSUE THREAD

**Issue by gregoiregavin** [edunumsec2/book#81]
### Page

Dans le répertoire GitHub

### Que s'est-il passé ?

Dans le .gitignore, on ignore _docs/ et _build/.

Or le dossier docs se retrouve dans le dépôt GitHub.

### Quel résultat était attendu ?

Je propose qu'on mette à jour le .gitignore, car l'output de 250Mo+ ne devrait pas être push/pull à chaque fois.

### Sur quel navigateur ?

Autre

### Quel format ?

Mobile

### Code of Conduct

- [x] J'accepte de suivre le code de conduite.

**Comment by elliotvaucher** [comment]
@gregoiregavin : en effet, excellente suggestion. T'as besoin d'aide sur un point particulier ?

**Comment by jppellet** [comment]
Bonne idée! Veille à détruire l'output et committer la destruction avant la mise à jour du gitignore.

**Comment by gregoiregavin** [comment]
Ok, je suis en train de faire un petit module pour Virginia et j'intègrerai également cette modif.
