### ISSUE TITLE
[Bug]: "No module names 'qrcode'"

### ISSUE THREAD

**Issue by gregoiregavin** [edunumsec2/book#90]
### Page

Extension video.py

### Que s'est-il passé ?

A l'exécution du book (enseigner ou apprendre), j'obtiens l'erreur suivante : 

```
gregoire@gregoire-ThinkPad-P14s-Gen-2i:~/Desktop/dev/book-modulo$ source .env/bin/activate; sphinx-build src/ens build -E
bash: .env/bin/activate: No such file or directory
Running Sphinx v4.2.0
loading translations [fr]... done

Extension error:
Could not import extension videos (exception: No module named 'qrcode')
```

Je n'avais pas cette erreur avant et je n'ose pas bidouiller l'extension video.py. 

Quelqu'un a une idée ?

### Quel résultat était attendu ?

Build fonctionnel.

### Sur quel navigateur ?

Firefox

### Quel format ?

Mobile, Desktop

### Code of Conduct

- [x] J'accepte de suivre le code de conduite.

**Comment by jppellet** [comment]
`source .env/bin/activate && pip install -r requirements.txt`

**Comment by gregoiregavin** [comment]
Oups, indeed... Merci @jppellet !
