### ISSUE TITLE
[Contenu]: Economie du numérique et moteur de recherche - source et clarification

### ISSUE THREAD

**Issue by Robb-Fr** [edunumsec2/book#95]
### Page

https://enseigner.modulo-info.ch/enjx1/grandes-thematiques/economie-numerique.html#pistes-pedagogiques

### Quel est le problème relevé ?

Dans la question e) du dossier 1.B, on mentionne le moteur de recherche Qwant comme "régulièrement pointé du doigt pour son partenariat avec Microsoft et son moteur de recherche Bing, dont sont issus une large part des résultats.", et elle n'est pas sourcée.

De même, cette mention me semble s'appliquer aussi à DuckDuckGo mais cela n'est pas mentionné.

### Quelle est votre suggestion ?

Serait-il possible de sourcer cette information ?

De plus, si ce reproche est fait à Qwant, serait-il envisageable de le faire également à DuckDuckGo ? https://www.bleepingcomputer.com/news/security/duckduckgo-browser-allows-microsoft-trackers-due-to-search-agreement/ 

### Code of Conduct

- [X] J'accepte de suivre le code de conduite.

**Comment by noflux** [comment]
Cette partie a été rédigée par l’équipe de rédaction des contenus relatifs aux enjeux sociaux, que j’ai validée après relecture. Il peut en effet être intéressant de généraliser afin d’insister sur la domination de Google, et sur sa concurrence limitée à Bing, Yandex et Baidu, le reste étant des associations de ces moteurs, à l’exemple de DuckDuckGo, qui utilisait aussi Yandex jusqu’à la guerre en Ukraine.  Google ne partage pas son moteur. Bing, en revanche, le fait, aussi avec Ecosia par exemple. La généralisation pourrait ainsi se faire à DuckDuckGo et Ecosia, qui comptent parmi les plus connus.

Dans le texte, c'est précisément ce qui est dit : DuckDuckGo est un métamoteur, ce qui n'exclue pas Bing. Cela peut néanmoins être précisé : "dont, Bing".

Parmi d’autres sources, pour Qwant : https://news.microsoft.com/europe/features/qwant-and-microsoft-announce-an-exclusive-partnership-for-a-unique-internet-research-experience/

Pour DuckDuckGo : https://help.duckduckgo.com/duckduckgo-help-pages/results/sources/ et https://www.protocol.com/bulletins/duckduckgo-yandex-ukraine

Pour Ecosia : https://info.ecosia.org/privacy
 
Merci pour la remarque.
Boris

**Comment by elliotvaucher** [comment]
@noflux @Robb-Fr : merci pour les retours.

J'ai fait les modifications suggérées dans le commit suivant : [99d362b87df501cbcb9c708d7aa5df379d5794b2](https://github.com/edunumsec2/book/commit/99d362b87df501cbcb9c708d7aa5df379d5794b2)

J'ai ajouté aussi la référence pour Ecosia dans ce commit là : [4e56bdd38e80106ffa670950bcfd6f647ce655cd](https://github.com/edunumsec2/book/commit/4e56bdd38e80106ffa670950bcfd6f647ce655cd). 

Dites-moi si ça vous convient et je publie.

**Comment by noflux** [comment]
Parfait. Pour Ecosia, je mettrais juste le lien sur "générés par Bing".

**Comment by elliotvaucher** [comment]
Ok, c'est fait ici : https://github.com/edunumsec2/book/commit/c997e2fb3295b87878d5d0a39da30e782e3f67f9

**Comment by Robb-Fr** [comment]
Superbe merci beaucoup !
